### PR TITLE
Patch2

### PR DESCRIPTION
**Pull request by ums-uk**

### CODE REVIEW

**Comment by kitwalker12** [comment]
hi @ums-uk 
Thanks for the update. I'm confused though. Which PR is the correct one. The one with the POST call or the one with the PUT call.

**Comment by ums-uk** [comment]
Hi,

Sorry I didn't realise this updated your code, it was just supposed to
update the fork copy. I haven't managed to get this working yet so best
ignore the PR. The PUT request should work but is causing a BP error - if I
get this working I will let you know.

Stephen Provis_Website Developer__Stephen Provis and Co_

t: 01206 804290
w: www.stephenprovis.com

**Comment by kitwalker12** [comment]
Before you test, just check if your brightpearl account has been updated to the latest version. They rollout platform updates in batches.

**Comment by ums-uk** [comment]
I will do, thank you

Stephen Provis_Website Developer__Stephen Provis and Co_

t: 01206 804290
w: www.stephenprovis.com

**Pull request closed without merging**
